import type { StackMapData } from "./types";

const createdAt = "2026-06-25T12:00:00.000Z";

export const seedData: StackMapData = {
  projects: [
    {
      id: "project-keymatch-pro",
      name: "KeyMatch Pro",
      type: "iOS app",
      status: "active",
      notes: "Sample manual project record.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "project-logit",
      name: "LogIT",
      type: "Android app",
      status: "active",
      notes: "Sample manual project record.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "project-home-inventory-vault",
      name: "Home Inventory Vault",
      type: "website",
      status: "active",
      notes: "Sample manual project record.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  tools: [
    {
      id: "tool-github",
      name: "GitHub",
      category: "code",
      websiteUrl: "https://github.com",
      loginUrl: "https://github.com/login",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Sample tool record only. No account connection.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-supabase",
      name: "Supabase",
      category: "database",
      websiteUrl: "https://supabase.com",
      loginUrl: "https://supabase.com/dashboard",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Sample tool record only. No account connection.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-openai",
      name: "OpenAI",
      category: "AI",
      websiteUrl: "https://openai.com",
      loginUrl: "https://platform.openai.com",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "usage",
      renewalDate: "",
      status: "active",
      notes: "Sample tool record only. No API key stored.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-moondream",
      name: "MoonDream",
      category: "AI",
      websiteUrl: "",
      loginUrl: "",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Sample tool record only.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-apple-developer",
      name: "Apple Developer",
      category: "app store",
      websiteUrl: "https://developer.apple.com",
      loginUrl: "https://developer.apple.com/account",
      accountEmail: "",
      paidStatus: "paid",
      monthlyCost: 0,
      annualCost: 99,
      billingCycle: "annual",
      renewalDate: "2026-09-01",
      status: "active",
      notes: "Sample subscription estimate only.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-google-play-console",
      name: "Google Play Console",
      category: "app store",
      websiteUrl: "https://play.google.com/console",
      loginUrl: "https://play.google.com/console",
      accountEmail: "",
      paidStatus: "paid",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "one-time",
      renewalDate: "",
      status: "active",
      notes: "Sample tool record only.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-tiktok",
      name: "TikTok",
      category: "marketing",
      websiteUrl: "https://www.tiktok.com",
      loginUrl: "https://www.tiktok.com/login",
      accountEmail: "",
      paidStatus: "free",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "none",
      renewalDate: "",
      status: "active",
      notes: "Sample marketing channel record.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-digen",
      name: "Digen",
      category: "marketing",
      websiteUrl: "",
      loginUrl: "",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Sample tool record only.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "tool-canva",
      name: "Canva",
      category: "design",
      websiteUrl: "https://www.canva.com",
      loginUrl: "https://www.canva.com/login",
      accountEmail: "",
      paidStatus: "trial",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Sample design tool record.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  relationships: [
    {
      id: "rel-keymatch-github",
      fromType: "project",
      fromId: "project-keymatch-pro",
      toType: "tool",
      toId: "tool-github",
      relationshipType: "uses",
      notes: "Sample relationship.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "rel-keymatch-apple",
      fromType: "project",
      fromId: "project-keymatch-pro",
      toType: "tool",
      toId: "tool-apple-developer",
      relationshipType: "publishes_to",
      notes: "Sample relationship.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "rel-logit-google",
      fromType: "project",
      fromId: "project-logit",
      toType: "tool",
      toId: "tool-google-play-console",
      relationshipType: "publishes_to",
      notes: "Sample relationship.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "rel-home-supabase",
      fromType: "project",
      fromId: "project-home-inventory-vault",
      toType: "tool",
      toId: "tool-supabase",
      relationshipType: "stores_data_in",
      notes: "Sample relationship. No connection is configured.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "rel-home-openai",
      fromType: "project",
      fromId: "project-home-inventory-vault",
      toType: "tool",
      toId: "tool-openai",
      relationshipType: "integrates_with",
      notes: "Sample relationship. No API key is stored.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "rel-keymatch-tiktok",
      fromType: "project",
      fromId: "project-keymatch-pro",
      toType: "tool",
      toId: "tool-tiktok",
      relationshipType: "markets_through",
      notes: "Sample relationship.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  subscriptions: [
    {
      id: "sub-apple-developer",
      toolId: "tool-apple-developer",
      vendorName: "Apple Developer",
      amount: 99,
      currency: "USD",
      billingCycle: "annual",
      nextRenewalDate: "2026-09-01",
      paymentMethod: "",
      status: "active",
      notes: "Sample subscription record only.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "sub-canva",
      toolId: "tool-canva",
      vendorName: "Canva",
      amount: 0,
      currency: "USD",
      billingCycle: "trial",
      nextRenewalDate: "",
      paymentMethod: "",
      status: "trial",
      notes: "Sample trial record only.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  suggestions: [],
  duplicateDecisions: [],
  integrationPlans: [
    {
      id: "integration-github",
      name: "GitHub",
      source: "github",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for repositories, languages, package clues, and deployment hints. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "integration-supabase",
      name: "Supabase",
      source: "supabase",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for projects, databases, edge functions, and storage buckets. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "integration-app-store",
      name: "Apple Developer / App Store",
      source: "app_store",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for app records and publishing relationships. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "integration-google-play",
      name: "Google Play Console",
      source: "google_play",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for Android app records and publishing relationships. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "integration-gmail",
      name: "Gmail Receipts",
      source: "gmail",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for renewal and receipt suggestions. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "integration-payment",
      name: "Payment / Subscription Sources",
      source: "payment",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for vendor and renewal suggestions. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "integration-airtable",
      name: "Airtable",
      source: "airtable",
      status: "planned",
      accessMode: "read_only",
      approvalRequired: true,
      notes: "Future read-only source for existing reference records if approved. Not connected.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
};
