import type { StackMapData } from "./types";

const createdAt = "2026-06-25T12:00:00.000Z";

export const seedData: StackMapData = {
  projects: [
    {
      id: "demo-project-logit",
      name: "LogIT",
      type: "mobile app",
      status: "active",
      notes:
        "Demo mobile app record. This sample shows why a private dependency map is useful for tracking stores, databases, AI tools, ads, subscriptions, and deployments.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-project-keymatch-pro",
      name: "KeyMatch Pro",
      type: "mobile app",
      status: "active",
      notes:
        "Demo app record based on a realistic indie-builder workflow. Public sample data only; no private account details are included.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-project-stackmap",
      name: "StackMap",
      type: "website",
      status: "active",
      notes:
        "Demo record for this local-first reference tool. StackMap tracks how projects, tools, subscriptions, and publishing accounts connect.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  tools: [
    {
      id: "demo-tool-visual-studio",
      name: "Visual Studio",
      category: "code",
      websiteUrl: "https://visualstudio.microsoft.com",
      loginUrl: "",
      accountEmail: "",
      paidStatus: "free",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "none",
      renewalDate: "",
      status: "active",
      notes: "Demo local development tool.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-github",
      name: "GitHub",
      category: "code",
      websiteUrl: "https://github.com",
      loginUrl: "https://github.com/login",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Demo source-code hosting tool. No account connection is configured.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-codex",
      name: "Codex",
      category: "AI",
      websiteUrl: "https://openai.com",
      loginUrl: "",
      accountEmail: "",
      paidStatus: "paid",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "usage",
      renewalDate: "",
      status: "active",
      notes: "Demo AI coding assistant record. No API key or token is stored.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-chatgpt",
      name: "ChatGPT",
      category: "AI",
      websiteUrl: "https://chatgpt.com",
      loginUrl: "https://chatgpt.com",
      accountEmail: "",
      paidStatus: "paid",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "monthly",
      renewalDate: "",
      status: "active",
      notes: "Demo planning and troubleshooting assistant.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-openai",
      name: "OpenAI",
      category: "AI",
      websiteUrl: "https://openai.com",
      loginUrl: "https://platform.openai.com",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "usage",
      renewalDate: "",
      status: "active",
      notes: "Demo API/platform dependency. No API key is stored.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-supabase",
      name: "Supabase",
      category: "database",
      websiteUrl: "https://supabase.com",
      loginUrl: "https://supabase.com/dashboard",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Demo backend/database tool. No project connection is configured.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-expo",
      name: "Expo.dev",
      category: "hosting",
      websiteUrl: "https://expo.dev",
      loginUrl: "https://expo.dev/accounts",
      accountEmail: "",
      paidStatus: "unknown",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "unknown",
      renewalDate: "",
      status: "active",
      notes: "Demo mobile build/deployment service.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-vercel",
      name: "Vercel",
      category: "hosting",
      websiteUrl: "https://vercel.com",
      loginUrl: "https://vercel.com/login",
      accountEmail: "",
      paidStatus: "free",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "none",
      renewalDate: "",
      status: "active",
      notes: "Demo web hosting/deployment platform.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-apple-developer",
      name: "Apple Developer",
      category: "app store",
      websiteUrl: "https://developer.apple.com",
      loginUrl: "https://developer.apple.com/account",
      accountEmail: "",
      paidStatus: "paid",
      monthlyCost: 0,
      annualCost: 99,
      billingCycle: "annual",
      renewalDate: "2026-08-31",
      status: "active",
      notes: "Demo publishing account. Uses public annual program price as sample data.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-google-play-console",
      name: "Google Play Console",
      category: "app store",
      websiteUrl: "https://play.google.com/console",
      loginUrl: "https://play.google.com/console",
      accountEmail: "",
      paidStatus: "paid",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "one-time",
      renewalDate: "",
      status: "active",
      notes: "Demo Android publishing account.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-revenuecat",
      name: "RevenueCat",
      category: "payment",
      websiteUrl: "https://www.revenuecat.com",
      loginUrl: "https://app.revenuecat.com",
      accountEmail: "",
      paidStatus: "free",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "usage",
      renewalDate: "",
      status: "active",
      notes: "Demo in-app purchase and subscription management tool.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-google-admob",
      name: "Google AdMob",
      category: "marketing",
      websiteUrl: "https://admob.google.com",
      loginUrl: "https://admob.google.com",
      accountEmail: "",
      paidStatus: "free",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "none",
      renewalDate: "",
      status: "active",
      notes: "Demo ads/monetization tool.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-tool-imdb",
      name: "IMDB",
      category: "database",
      websiteUrl: "https://www.imdb.com",
      loginUrl: "",
      accountEmail: "",
      paidStatus: "free",
      monthlyCost: 0,
      annualCost: 0,
      billingCycle: "none",
      renewalDate: "",
      status: "active",
      notes: "Demo movie and TV reference data dependency.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  relationships: [
    {
      id: "demo-rel-logit-visual-studio",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-visual-studio",
      relationshipType: "uses",
      notes: "Local development environment.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-github",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-github",
      relationshipType: "uses",
      notes: "Source code repository.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-codex",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-codex",
      relationshipType: "assists_with",
      notes: "AI coding help during development.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-chatgpt",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-chatgpt",
      relationshipType: "uses",
      notes: "Planning and troubleshooting help.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-expo",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-expo",
      relationshipType: "deploys_to",
      notes: "Mobile build/deployment workflow.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-vercel",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-vercel",
      relationshipType: "deploys_to",
      notes: "Related web/API deployment target.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-supabase",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-supabase",
      relationshipType: "stores_data_in",
      notes: "Backend database/storage dependency.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-openai",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-openai",
      relationshipType: "integrates_with",
      notes: "AI platform dependency. No API key stored.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-imdb",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-imdb",
      relationshipType: "depends_on",
      notes: "Movie and TV reference data source.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-admob",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-google-admob",
      relationshipType: "integrates_with",
      notes: "Ads and monetization workflow.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-revenuecat",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-revenuecat",
      relationshipType: "integrates_with",
      notes: "In-app purchase and subscription management.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-apple",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-apple-developer",
      relationshipType: "publishes_to",
      notes: "iOS publishing account.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-logit-google-play",
      fromType: "project",
      fromId: "demo-project-logit",
      toType: "tool",
      toId: "demo-tool-google-play-console",
      relationshipType: "publishes_to",
      notes: "Android publishing account.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-keymatch-github",
      fromType: "project",
      fromId: "demo-project-keymatch-pro",
      toType: "tool",
      toId: "demo-tool-github",
      relationshipType: "uses",
      notes: "Source code repository.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-keymatch-supabase",
      fromType: "project",
      fromId: "demo-project-keymatch-pro",
      toType: "tool",
      toId: "demo-tool-supabase",
      relationshipType: "stores_data_in",
      notes: "Backend data dependency.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-keymatch-apple",
      fromType: "project",
      fromId: "demo-project-keymatch-pro",
      toType: "tool",
      toId: "demo-tool-apple-developer",
      relationshipType: "publishes_to",
      notes: "iOS publishing account.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-keymatch-google-play",
      fromType: "project",
      fromId: "demo-project-keymatch-pro",
      toType: "tool",
      toId: "demo-tool-google-play-console",
      relationshipType: "publishes_to",
      notes: "Android publishing account.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-stackmap-github",
      fromType: "project",
      fromId: "demo-project-stackmap",
      toType: "tool",
      toId: "demo-tool-github",
      relationshipType: "uses",
      notes: "Source code repository.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-stackmap-codex",
      fromType: "project",
      fromId: "demo-project-stackmap",
      toType: "tool",
      toId: "demo-tool-codex",
      relationshipType: "assists_with",
      notes: "AI coding help while building StackMap.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-rel-stackmap-vercel",
      fromType: "project",
      fromId: "demo-project-stackmap",
      toType: "tool",
      toId: "demo-tool-vercel",
      relationshipType: "deploys_to",
      notes: "Possible public web preview deployment.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  subscriptions: [
    {
      id: "demo-sub-apple-developer",
      toolId: "demo-tool-apple-developer",
      vendorName: "Apple Developer",
      amount: 99,
      currency: "USD",
      billingCycle: "annual",
      nextRenewalDate: "2026-08-31",
      paymentMethod: "",
      status: "active",
      notes: "Demo subscription record only.",
      createdAt,
      updatedAt: createdAt,
    },
    {
      id: "demo-sub-chatgpt",
      toolId: "demo-tool-chatgpt",
      vendorName: "ChatGPT",
      amount: 20,
      currency: "USD",
      billingCycle: "monthly",
      nextRenewalDate: "",
      paymentMethod: "",
      status: "active",
      notes: "Demo recurring subscription. Replace with your own details if tracking real data.",
      createdAt,
      updatedAt: createdAt,
    },
  ],
  suggestions: [],
  duplicateDecisions: [],
};
