import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const outputDir = join(process.cwd(), "generated");
const outputPath = join(outputDir, "github-suggestions.json");

function runGh(args) {
  return execFileSync("gh", args, {
    cwd: process.cwd(),
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
}

function repoType(repo) {
  const name = repo.name.toLowerCase();
  const description = (repo.description ?? "").toLowerCase();
  const combined = `${name} ${description}`;

  if (combined.includes("api") || combined.includes("backend")) return "backend";
  if (combined.includes("site") || combined.includes("web")) return "website";
  if (combined.includes("ios")) return "iOS app";
  if (combined.includes("android")) return "Android app";
  if (combined.includes("marketing")) return "marketing";
  return "other";
}

function projectSuggestion(repo, detectedAt) {
  const language = repo.primaryLanguage?.name ?? "";
  const topics = (repo.repositoryTopics ?? [])
    .map((topic) => topic.name)
    .filter(Boolean)
    .join(", ");

  return {
    source: "github",
    entityType: "project",
    status: "pending",
    confidence: 0.82,
    detectedFields: {
      name: repo.name,
      type: repoType(repo),
      status: "active",
      sourceName: repo.name,
      sourceUrl: repo.url ?? "",
      sourceVisibility: repo.isPrivate ? "private" : "public",
      primaryLanguage: language,
      lastDetectedAt: detectedAt,
      notes: [
        "Detected from GitHub repository metadata.",
        repo.description ? `Description: ${repo.description}` : "",
        language ? `Primary language: ${language}` : "",
        topics ? `Topics: ${topics}` : "",
        repo.url ? `URL: ${repo.url}` : "",
        repo.isPrivate ? "Private repository." : "Public repository.",
      ]
        .filter(Boolean)
        .join(" "),
    },
    notes:
      "Generated by local GitHub CLI sync. No repository contents were cloned or scanned.",
  };
}

function githubRelationshipSuggestion(repo, detectedAt) {
  return {
    source: "github",
    entityType: "relationship",
    status: "pending",
    confidence: 0.86,
    detectedFields: {
      name: `${repo.name} uses GitHub`,
      fromType: "project",
      fromName: repo.name,
      fromSourceUrl: repo.url ?? "",
      toType: "tool",
      toName: "GitHub",
      toSourceUrl: "https://github.com",
      relationshipType: "uses",
      lastDetectedAt: detectedAt,
      notes: "Detected because this project was listed as a GitHub repository.",
    },
    notes:
      "Generated by local GitHub CLI sync. Accept only after the matching project and GitHub tool records exist.",
  };
}

function githubToolSuggestion(detectedAt) {
  return {
    source: "github",
    entityType: "tool",
    status: "pending",
    confidence: 0.9,
    detectedFields: {
      name: "GitHub",
      category: "code",
      websiteUrl: "https://github.com",
      loginUrl: "https://github.com/login",
      paidStatus: "unknown",
      status: "active",
      sourceName: "GitHub",
      sourceUrl: "https://github.com",
      sourceVisibility: "account",
      primaryLanguage: "",
      lastDetectedAt: detectedAt,
      notes: "Detected because GitHub repository metadata was synced locally.",
    },
    notes: "Generated by local GitHub CLI sync.",
  };
}

try {
  runGh(["auth", "status"]);
  const repoJson = runGh([
    "repo",
    "list",
    "--limit",
    "200",
    "--json",
    "name,description,isPrivate,url,primaryLanguage,repositoryTopics,updatedAt",
  ]);
  const repos = JSON.parse(repoJson);
  const generatedAt = new Date().toISOString();
  const suggestions = [
    githubToolSuggestion(generatedAt),
    ...repos.map((repo) => projectSuggestion(repo, generatedAt)),
    ...repos.map((repo) => githubRelationshipSuggestion(repo, generatedAt)),
  ];

  mkdirSync(outputDir, { recursive: true });
  writeFileSync(
    outputPath,
    JSON.stringify(
      {
        app: "StackMap",
        kind: "suggestion-import",
        source: "github",
        generatedAt,
        notes:
          "Generated locally with GitHub CLI. Import into StackMap Suggestions for manual approval.",
        suggestions,
      },
      null,
      2,
    ),
  );

  console.log(`Wrote ${suggestions.length} suggestions to ${outputPath}`);
} catch (error) {
  console.error("GitHub sync failed.");
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}
